version: "3"
services:
    php:
      image: ${DOCKER_PHP_IMAGE}
      ports:
      - 8081-8082:80
      depends_on:
        - mysql
    mysql:
      image: ${DOCKER_DB_IMAGE}
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: mydatabase
        MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: {}
