version: "3"
services:
    php:
      image: mudassir12/php:${BUILD_NUMBER}
      ports:
      - 8081-8082:80
      depends_on:
        - mysql
    mysql:
      image: mudassir12/mysql:${BUILD_NUMBER}
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: mydatabase
        MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: {}
