version: "3"
services:
    php:
      image: ${PHP_IMAGE_NAME}
      ports:
      - 8081-8082:80
      depends_on:
        - mysql
    mysql:
      image: ${DB_IMAGE_NAME}
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_DATABASE: mydatabase
        MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: {}
